apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
  labels:
    app: blog-app
spec:
  type: ClusterIP
  selector:
    app: blog-app
  ports:
    - name: http
      port: 80
      targetPort: 8080

